# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('state', models.BooleanField(verbose_name='操作类型')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
            ],
        ),
    ]
