# Generated by Django 2.0.7 on 2018-11-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataname', models.CharField(max_length=32, verbose_name='数据名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('filename', models.CharField(max_length=20, verbose_name='文件名称')),
                ('number', models.IntegerField(verbose_name='导入数量')),
                ('bywho', models.CharField(max_length=20, verbose_name='上传人')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
