# Generated by Django 2.0.7 on 2018-11-10 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0003_auto_20181106_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='组名')),
                ('group_user', models.ManyToManyField(related_name='用户', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='权限')),
            ],
        ),
        migrations.AddField(
            model_name='admingroup',
            name='permission',
            field=models.ManyToManyField(to='major.AdminPermission', verbose_name='权限'),
        ),
    ]
